[versions]
leakcanaryAndroid = "2.14"
sdk_version = "1.0.4"

agp = "8.1.4"
kotlin = "1.9.20"

# Android
coreKtx = "1.8.0"
fragment = "1.5.0"
material = "1.1.0"

# Compose
composeUi = "1.5.0"
activityCompose = "1.7.0"
navigationCompose = "2.5.0"

# Test
junit = "4.13.2"
junitVersion = "1.1.3"
espressoCore = "3.4.0"

[libraries]
# Android X
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }

# Compose (BOM 없이 개별 버전)
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "composeUi" }
androidx-ui-text = { group = "androidx.compose.ui", name = "ui-text", version.ref = "composeUi" }
androidx-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "composeUi" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

# Debugging
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanaryAndroid" }

# Test
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

